#obj-m += driver.o
obj-m += major_minor.o
#obj-m += static_major_minor.o


KDIR = /lib/modules/$(shell uname -r)/build
 
 
all:
	make -C $(KDIR)  M=$(shell pwd) modules
 
clean:
	make -C $(KDIR)  M=$(shell pwd) clean
